apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: sparkclusters.spark.k8s.io
spec:
  group: spark.k8s.io
  names:
    kind: SparkCluster
    plural: sparkclusters
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterPrefix:
              description: PodName  string `json:"podName"` Replicas *int32 `json:"replicas"`
              type: string
            nfs:
              type: boolean
            ports:
              items:
                type: object
              type: array
            pvcEnable:
              type: boolean
            resources:
              type: object
            slaveNum:
              format: int64
              type: integer
          required:
          - clusterPrefix
          - slaveNum
          type: object
        status:
          properties:
            createTime:
              description: CreateTime represents time when the SparkCluster was created.
              format: date-time
              type: string
            endpoints:
              description: Endpoints for pods
              type: object
            exposedPorts:
              description: Exposed Port for UI
              items:
                type: object
              type: array
            phase:
              description: Phase show the running phase of SparkCluster.
              type: string
          required:
          - phase
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
