apiVersion: spark.k8s.io/v1alpha1
kind: SparkCluster
metadata:
  labels:
    app: hadoop-spark-cluster
  name: cluster-1
spec:
  # Add fields here
  slaveNum: 3
  pvcEnable: False
  
  # ports:
  #   - port: 9000
  #     name: hdfs

  # resources:
  #   limits:
  #     cpu: "2"
  #     memory: "2000Mi"
  #   requests:
  #     cpu: "1"
  #     memory: "1500Mi"

  # nfs: True

